### ISSUE TITLE
I can't run it on my PC

### ISSUE THREAD

**Issue by OMGchangeMYusername** [GummiBoat/BuddelSpam#1]
What's this :wink: 
and btw check Skype :anguished: i'm loonely

**Comment by GummiBoat** [comment]
lmao

**Comment by OMGchangeMYusername** [comment]
is this some sort of project? or is it just idk?

**Comment by GummiBoat** [comment]
this was just a try to figure out how github works

**Comment by OMGchangeMYusername** [comment]
oh =D
i thought you were making a mod for Wurst or something :P
